export default {
    namespaced: true,
    getters: {
        gameData: (state, getters, rootState) => rootState.game.data,
        gameState: (state, getters) => getters.gameData.gameState,
        hand: (state, getters) => getters.gameData.hand,
        canDecide: (state, getters) => getters.gameData.canDecide,
        hasDecided: (state, getters) => getters.gameData.hasDecided,
        myDecision: (state, getters) => getters.gameData.myDecision,
        phase: (state, getters) => getters.gameState.phase,
        isDeclarationPhase: (state, getters) => getters.phase === 'declaration',
        isShowdown: (state, getters) => getters.phase === 'showdown' || getters.phase === 'roundEnd',
        isGameOver: (state, getters) => getters.gameState.isGameOver,
        participants: (state, getters) => getters.gameState.participants,
        decisions: (state, getters) => getters.gameState.decisions,
        showdownResult: (state, getters) => getters.gameState.showdownResult,
        pot: (state, getters) => getters.gameState.pot,
        round: (state, getters) => getters.gameState.round,
        ante: (state, getters) => getters.gameState.ante,
        maxOwed: (state, getters) => getters.gameState.maxOwed,
        getParticipant: (state, getters) => (playerId) =>
            getters.participants.find(p => p.playerId === playerId),
        cardCount: (state, getters) => getters.gameState.cardCount,
        bloodyGuts: (state, getters) => getters.gameState.bloodyGuts,
        deckHand: (state, getters) => getters.gameState.deckHand,
        deckCardsRevealed: (state, getters) => getters.gameState.deckCardsRevealed,
        deckCardsTotal: (state, getters) => getters.gameState.deckCardsTotal,
        deckWon: (state, getters) => getters.showdownResult?.deckWon,
    },
}
